
Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Psmb.CreateNodeButton:
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Psmb.CreateNodeButton: true
