
Neos:
  Neos:
    typoScript:
      autoInclude:
        Psmb.CreateNodeButton: true
    userInterface:
      translation:
        autoInclude:
          Psmb.CreateNodeButton:
            - 'NodeTypes/*'
